[package]
name = "wasm-gc-capi"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[lib]
crate-type = ['cdylib']

[dependencies]
wasm-gc-api = { path = '../wasm-gc-api' }
cfg-if = "0.1"
wasm-bindgen = { version = "0.2", optional = true }
